version: '2'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'
    volumes:
      - type: bind
        source: /Users/gauravgupta/ril/Docker-Flask-MySQL/experiment_path
        target: /Photos-Docker-Flask/experiment_path

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: insta_admin
      MYSQL_PASSWORD: insta2018
      MYSQL_DATABASE: insta_db